import { BottomSheetModal } from '@gorhom/bottom-sheet';
import { forwardRef, useEffect, useState } from 'react';
import { ScrollView, View } from 'react-native';
import { Banner } from '@/design/components/Banner';
import { Chip } from '@/design/components/Chip';
import { Sheet } from '@/design/components/Sheet';
import { TintedButton } from '@/design/components/TintedButton';
import { useTheme } from '@/design/useTheme';
import { useI18n } from '@/i18n/I18nProvider';
import { isApiError } from '@/api/http';
import type { ColumnMeta } from '../types';
import { FormField } from './FormField';

interface FieldState {
  value: string;
  isNull: boolean;
}

interface Props {
  columns: ColumnMeta[];
  /** Presente = editar um registro existente (campos pré-preenchidos); ausente = "Nova linha". */
  initial?: Record<string, unknown> | null;
  onSubmit: (values: Record<string, unknown>) => Promise<void> | void;
}

function buildInitialState(columns: ColumnMeta[], initial?: Record<string, unknown> | null): Record<string, FieldState> {
  const state: Record<string, FieldState> = {};
  for (const c of columns) {
    const v = initial ? initial[c.name] : undefined;
    state[c.name] = { value: v === null || v === undefined ? '' : String(v), isNull: initial ? v === null : false };
  }
  return state;
}

// Formulário de registro — usado tanto pra "Nova linha" (Dados tab) quanto pra "Editar" a
// partir do menu da linha (DataGrid). Toda coluna mostra tipo e obrigatoriedade (DB-MOBILE.md
// item 1 do lote de retoques) em vez de um form solto sem pista nenhuma do schema.
export const RecordFormSheet = forwardRef<BottomSheetModal, Props>(function RecordFormSheet(
  { columns, initial, onSubmit },
  ref
) {
  const { space } = useTheme();
  const { t } = useI18n();
  const isEdit = !!initial;
  const [values, setValues] = useState<Record<string, FieldState>>(() => buildInitialState(columns, initial));
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setValues(buildInitialState(columns, initial));
    setError(null);
  }, [columns, initial]);

  function set(name: string, patch: Partial<FieldState>) {
    setValues((prev) => ({ ...prev, [name]: { ...prev[name], ...patch } }));
  }

  async function submit() {
    const editable = columns.filter((c) => !(c.isAutoIncrement && !isEdit));
    const required = editable.filter((c) => !c.nullable && c.default == null && !c.isAutoIncrement);
    for (const c of required) {
      const f = values[c.name];
      if (!f || f.isNull || f.value.trim() === '') {
        setError(t('dbclient.requiredField', { field: c.name }));
        return;
      }
    }
    const out: Record<string, unknown> = {};
    for (const c of editable) {
      const f = values[c.name];
      if (!f) continue;
      out[c.name] = f.isNull ? null : f.value;
    }
    setSaving(true);
    setError(null);
    try {
      await onSubmit(out);
      // "Nova linha" reabre com o MESMO `initial` (null) da vez anterior — o efeito acima só
      // reseta os campos quando a referência de `initial`/`columns` muda, então sem isso o
      // formulário reabria com o que foi digitado da última vez (bug real reportado pelo
      // usuário). Editar não precisa disso: cada linha manda um `initial` novo, o efeito já
      // limpa sozinho.
      if (!isEdit) setValues(buildInitialState(columns, null));
    } catch (e) {
      setError(isApiError(e) ? e.message : e instanceof Error ? e.message : String(e));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Sheet ref={ref} title={isEdit ? t('dbclient.editRecord') : t('dbclient.newRecord')} snapPoints={['80%']}>
      <ScrollView contentContainerStyle={{ paddingBottom: space.xl }}>
        {columns.map((c) => {
          const f = values[c.name] ?? { value: '', isNull: false };
          const locked = c.isAutoIncrement && !isEdit;
          const hint = `${c.type}${c.nullable ? ` · ${t('dbclient.optional')}` : ` · ${t('dbclient.required')}`}${c.isPrimaryKey ? ' · PK' : ''}`;
          return (
            <View key={c.name} style={{ opacity: locked ? 0.5 : 1 }}>
              <FormField
                label={`${c.name} — ${hint}`}
                value={f.isNull ? '' : f.value}
                onChangeText={(v) => set(c.name, { value: v, isNull: false })}
                placeholder={locked ? t('dbclient.autoGenerated') : c.type}
                editable={!locked && !f.isNull}
              />
              {c.nullable && !locked ? (
                <View style={{ marginTop: -6, marginBottom: space.sm, alignItems: 'flex-start' }}>
                  <Chip label="NULL" active={f.isNull} onPress={() => set(c.name, { isNull: !f.isNull })} />
                </View>
              ) : null}
            </View>
          );
        })}
        {error ? (
          <View style={{ marginBottom: space.sm }}>
            <Banner tone="error" title={error} />
          </View>
        ) : null}
        <View style={{ marginTop: space.sm }}>
          <TintedButton icon="check" label={t('common.save')} onPress={submit} busy={saving} />
        </View>
      </ScrollView>
    </Sheet>
  );
});
