import {
  X,
  Check,
  ChevronRight,
  Plus,
  Minus,
  Undo2,
  Redo2,
  Trash2,
  CircleEllipsis,
  Info,
  Sparkles,
  Pencil,
  Link,
  Copy,
  Code,
  TableColumnsSplit,
  ArrowRightLeft,
  Palette,
  SlidersHorizontal,
  Shapes,
  Type,
  MessageSquare,
  Table,
  Diamond,
  Heading,
  Bold,
  Italic,
  List,
  ListOrdered,
  ListChecks,
  Quote,
  Workflow,
  Scan,
  Share2,
  Image,
  Library,
  Settings,
  Hand,
  Eraser,
  MousePointer2,
  Square,
  Circle,
  MoveUpRight,
  Slash,
  Grid3x3,
  Dot,
  Pipette,
  Spline,
  Route,
  TextAlignStart,
  TextAlignCenter,
  TextAlignEnd,
  BringToFront,
  SendToBack,
  ChevronUp,
  ChevronDown,
  SquareDashedMousePointer,
  Group as GroupIcon,
  Ungroup as UngroupIcon,
  FileText,
  Database,
} from 'lucide-react-native';
import { useTheme } from './useTheme';

// Ícones vêm do lucide-react-native (SVG puro, mesma base do runtime — react-native-svg —
// então roda sem plugin nativo extra, inclusive no Expo Go). Registro pequeno de propósito:
// adicione um ícone por vez, quando uma feature precisar, escolhendo o equivalente mais
// próximo do desenho do protótipo (editor-mermaid.html, registro `ICO`) em vez de inventar um
// novo. Um ícone por *significado*, não por contexto — reaproveitar o mesmo ícone pra ações
// diferentes (ex.: "check" pra IA e pra Nome) é o bug que gerou esse registro maior. Ver
// docs/03-design-system.md.
const ICONS = {
  close: X,
  check: Check,
  chevronRight: ChevronRight,
  plus: Plus,
  minus: Minus,
  undo: Undo2,
  redo: Redo2,
  trash: Trash2,
  menu: CircleEllipsis,
  info: Info,
  spark: Sparkles,
  pencil: Pencil,
  link: Link,
  copy: Copy,
  code: Code,
  columns: TableColumnsSplit,
  swap: ArrowRightLeft,
  palette: Palette,
  sliders: SlidersHorizontal,
  shapes: Shapes,
  type: Type,
  comment: MessageSquare,
  table: Table,
  cardinality: Diamond,
  heading: Heading,
  bold: Bold,
  italic: Italic,
  list: List,
  listOrdered: ListOrdered,
  listChecks: ListChecks,
  quote: Quote,
  flow: Workflow,
  scan: Scan,
  share: Share2,
  image: Image,
  library: Library,
  settings: Settings,
  hand: Hand,
  eraser: Eraser,
  pointer: MousePointer2,
  square: Square,
  circle: Circle,
  moveUpRight: MoveUpRight,
  slash: Slash,
  grid: Grid3x3,
  dot: Dot,
  pipette: Pipette,
  spline: Spline,
  route: Route,
  alignLeft: TextAlignStart,
  alignCenter: TextAlignCenter,
  alignRight: TextAlignEnd,
  bringToFront: BringToFront,
  sendToBack: SendToBack,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  multiSelect: SquareDashedMousePointer,
  group: GroupIcon,
  ungroup: UngroupIcon,
  document: FileText,
  database: Database,
} as const;

export type IconName = keyof typeof ICONS;

interface Props {
  name: IconName;
  size?: number;
  color?: string;
}

export function Icon({ name, size = 22, color }: Props) {
  const { colors } = useTheme();
  const Cmp = ICONS[name];
  return <Cmp size={size} color={color ?? colors.blue} strokeWidth={1.8} />;
}
